from LinkedList import LinkedList

ll = LinkedList()

print("add to front: ")
ll.add_first(5)
ll.add_first(7)
ll.display()
print("list size:", ll.get_size())
print("add to the end: ")
ll.add_last(10)
ll.add_last(20)
ll.display()
print("list size:", ll.get_size())
print("remove from the front: ")
ll.remove_first()
ll.display()
print("list size:", ll.get_size())
print("remove from the end: ")
ll.remove_last()
ll.display()
print("list size:", ll.get_size())
lst = list(ll.iterate())
print(lst)